PO = on_core on_status on_network on_reboot on_portmapping on_base on_opennet_1 on_opennet_2

include ../../build/config.mk
include ../../build/module.mk
# add this to enable compilation of c(++) code
#include ../../build/gccconfig.mk

compile:
	# Commands to compile and link your C-code
	# and to install them under the dist/ hierarchy

clean: luaclean
	# Commands to clean your compiled objects

