PO = on_openvpn on_gateways

include ../../build/config.mk
include ../../build/module.mk
# add this to enable compilation of c(++) code
#include ../../build/gccconfig.mk

compile:
	# Commands to compile and link your C-code
	# and to install them under the dist/ hierarchy

clean: luaclean
	# Commands to clean your compiled objects

