#!/bin/sh
#
# In der ath9k-Version der Firmware v0.5.1 bleibt der Master einer Verbindung manchmal haengen.
# Symptome: alle Clients trennen sich nach einer Weile. Zuvor bleibt der TX-Zaehler auf der Master-Seite stehen.
# Loesung: "wifi" fuer neue Initialisierung des Masters
# Anwendung: scp on_workaround_wifi_master_hangs root@192.168.X.Y:/etc/cron.minutely/
#
# VORSICHT: das WLAN-Interface _muss_ OLSR-Verkehr fuehren - ansonsten wird das Interface im Minutentakt neugestartet
#
# Dieses Skript sollte im Minuten-Takt ausgefuehrt werden.

set -eu

WIFI_DEVICE="wlan0"
LAST_RX_COUNTER_FILE="/tmp/$(basename "$0")-${WIFI_DEVICE}.cache"
RESET_TIMESTAMP_FILE="/tmp/$(basename "$0")-${WIFI_DEVICE}.timestamp"
MINIMUM_RESET_PERIOD_SECONDS=900


is_wifi_master() {
	iwinfo "$WIFI_DEVICE" info | grep -qw "Mode: Master"
}


is_reset_period_elapsed() {
	# keine Datei? Reset ist erlaubt ...
	[ -e "$RESET_TIMESTAMP_FILE" ] || return 0
	local timestamp
	local now
	timestamp=$(cat "$RESET_TIMESTAMP_FILE")
	now=$(date +%s)
	# schon abgelaufen?
	[ "$((timestamp + MINIMUM_RESET_PERIOD_SECONDS))" -lt "$now" ] && return 0
	return 1
}


get_rx_counters() {
	iwinfo "$WIFI_DEVICE" assoclist | grep -w "RX:"
}


# Abbruchbedingungen?
is_wifi_master || exit 0
is_reset_period_elapsed || exit 0


if [ -e "$LAST_RX_COUNTER_FILE" ] && get_rx_counters | cmp -s "$LAST_RX_COUNTER_FILE"; then
	# die Zaehler sind stehengeblieben
	on-function add_banner_event "wifi master hangs"
	date +%s >"$RESET_TIMESTAMP_FILE"
	# es scheint Situationen zu geben, in denen hostapd sich selbst blockiert
	# siehe https://dev.opennet-initiative.de/ticket/184
	killall -q -TERM hostapd
	wifi
else
	# neue Zaehler speichern
	get_rx_counters >"$LAST_RX_COUNTER_FILE"
fi
